apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: job-match-ingress
  namespace: job-match
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.jobmatch.com
    - www.jobmatch.com
    secretName: jobmatch-tls
  rules:
  - host: api.jobmatch.com
    http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: job-match-backend
            port:
              number: 8080
      - path: /ws
        pathType: Prefix
        backend:
          service:
            name: job-match-backend
            port:
              number: 8080
  - host: www.jobmatch.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: job-match-frontend
            port:
              number: 80
  - host: ai.jobmatch.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: job-match-ai-service
            port:
              number: 5000