$kind: http-request
name: "{{baseUrl}}/api/v1/applications/apply"
url: "{{baseUrl}}/api/v1/applications/apply"
method: POST
body:
  type: json
  content: "{\r\n  \"jobId\": 1\r\n}"
auth:
  type: bearer
  credentials:
    token: "{{seekerToken}}"
order: 6000
